# ローカルテストのためのdocker-compose!!
# ライブには vercel build をして vercel deploy するよ。.github/workflows/deploy.yml を見てね。

version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/src
    working_dir: /src/dashboard
    ports:
    - "5173:5173"
    #command: sh -c "npm install &&npm run serve"
    command: yarn dev --host