version: '3'
# M1/M2 mac等のarm64環境で動作させるために、platformをamd64に指定したバージョン。

# 起動するときは以下のようにprofileを指定してください！！
# chatもadminも両方起動する場合 >  docker-compose -f docker-compose_macm1.yml --profile live up 
# * chatはビルドに1hはみておいてください！
# adminだけを起動する場合 > docker-compose  -f docker-compose_macm1.yml --profile admin up 

services:
  app:
    container_name: ihi_app
    build: ./app
    platform: linux/amd64
    volumes:
     - ./app/source:/django
    ports:
     - 2343:8000
    image: app:django
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    profiles:
      - admin
      - live
    depends_on:
      db:
        condition: service_started
  
  db:
    image: postgres:13
    # platform: linux/amd64
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ihi_db
      - POSTGRES_USER=ihi
      - POSTGRES_PASSWORD=ihi
    ports:
      - 2849:5432
    container_name: ihi_postgres

  pgadmin4:
    image: dpage/pgadmin4
    
    ports:
        - 8888:80
    volumes:
        - ./pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: r-takahashi@bizfreak.co.jp
        PGADMIN_DEFAULT_PASSWORD: r-takahashi
    depends_on:
      - db

