# Generated by Django 4.2.2 on 2023-06-14 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='environmental_type_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.CreateModel(
            name='MDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='デバイス名')),
                ('device_number', models.IntegerField(verbose_name='デバイス型番')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('device_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, to='ihiapp.devicetype', verbose_name='デバイスの種類ID')),
                ('environmental_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.environmentaltype', verbose_name='環境の種類ID')),
            ],
            options={
                'verbose_name': 'マスタデバイス一覧',
                'verbose_name_plural': 'マスタデバイス一覧',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='m_device_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.mdevice', verbose_name='マスタデバイスID'),
        ),
    ]
