# Generated by Django 4.2.2 on 2023-06-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0002_remove_device_device_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='input_source',
            field=models.IntegerField(choices=[(1, 'DEVICE'), (2, 'MANUAL')], default=1, verbose_name='入力元'),
        ),
    ]
