# Generated by Django 4.2.2 on 2023-06-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0003_device_input_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electric_unit_price', models.IntegerField(default=0, verbose_name='電気(円/kWh)')),
                ('water_unit_price', models.IntegerField(default=0, verbose_name='水(円/m3)')),
                ('fuel_unit_price', models.IntegerField(default=0, verbose_name='燃料(円/m3)')),
                ('co2_unit_price', models.IntegerField(default=0, verbose_name='CO2(円/t-CO2)')),
                ('electric_unit_co2', models.FloatField(default=0, verbose_name='電気(t-CO2/kWh)')),
                ('fuel_unit_co2', models.FloatField(default=0, verbose_name='燃料(t-CO2/m3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.device', verbose_name='デバイス')),
            ],
            options={
                'verbose_name': '単価情報',
                'verbose_name_plural': '単価情報一覧',
            },
        ),
    ]
