# Generated by Django 4.2.2 on 2023-07-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0004_deviceunitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceunitprice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.device', unique=True, verbose_name='デバイス'),
        ),
    ]
