# Generated by Django 4.2.3 on 2023-07-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0005_alter_deviceunitprice_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceunitprice',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.device', verbose_name='デバイス'),
        ),
    ]
