# Generated by Django 4.2.3 on 2023-07-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0006_alter_deviceunitprice_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('target_type', models.CharField(choices=[('electric', '電気'), ('water', '水'), ('fuel', '燃料'), ('co2', 'CO2')], max_length=10, verbose_name='目標タイプ')),
                ('target_value', models.FloatField(verbose_name='目標値')),
                ('target_price', models.IntegerField(verbose_name='目標金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '月次目標',
                'verbose_name_plural': '月次目標一覧',
                'unique_together': {('user_id', 'year', 'month', 'target_type')},
            },
        ),
    ]
