# Generated by Django 4.2.3 on 2023-08-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0007_monthlycosttarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='edge_device_number',
        ),
        migrations.AddField(
            model_name='device',
            name='device_number',
            field=models.IntegerField(null=True, verbose_name='デバイス型番'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.devicetype', verbose_name='デバイスの種類ID'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='デバイス名'),
        ),
        migrations.AddField(
            model_name='device',
            name='pushlog_unique_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='PUSHLOGのユニークID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='m_device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.mdevice', verbose_name='マスタデバイスID'),
        ),
        migrations.AlterField(
            model_name='environmentaltype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='環境の種類名'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('environmental_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.environmentaltype', verbose_name='環境タイプID')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('is_activated', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='gateway_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gateway', verbose_name='ゲートウェイID'),
        ),
        migrations.AddField(
            model_name='device',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.unit', verbose_name='単位ID'),
        ),
    ]
