# Generated by Django 4.2.3 on 2023-08-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0008_remove_device_edge_device_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='デバイス型番'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.devicetype', verbose_name='デバイスの種類ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gateway_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gateway', verbose_name='ゲートウェイID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pushlog_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='PUSHLOGのユニークID'),
        ),
    ]
