# Generated by Django 4.2.3 on 2023-09-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0009_alter_device_device_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'SalesType',
                'verbose_name_plural': 'SalesTypes',
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_value', models.IntegerField(verbose_name='売上値')),
                ('sales_date', models.DateField(verbose_name='売上日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sales_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.salestype', verbose_name='売上タイプID')),
            ],
            options={
                'verbose_name': 'DailySales',
                'verbose_name_plural': 'DailySales',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='sales_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.salestype', verbose_name='売上種別ID'),
        ),
    ]
