# Generated by Django 4.2.4 on 2023-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0010_salestype_dailysales_device_sales_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_source_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='データ取得対象名'),
        ),
        migrations.AddField(
            model_name='device',
            name='enable_data_collection',
            field=models.BooleanField(default=False, verbose_name='データ収集を有効にするか'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='デバイス名'),
        ),
    ]
