# Generated by Django 4.2.3 on 2023-09-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0011_device_data_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataperdate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='dataperhour',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='datapermonth',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='dataperyear',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='devicedataperdate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='devicedataperhour',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='devicedatapermonth',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='devicedataperyear',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='jcreditapplication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jcreditapplication',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='mdevice',
            name='device_type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.devicetype', verbose_name='デバイスの種類ID'),
        ),
        migrations.AlterField(
            model_name='mdevice',
            name='environmental_type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.environmentaltype', verbose_name='環境の種類ID'),
        ),
        migrations.AlterField(
            model_name='mdevice',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='デバイス名'),
        ),
    ]
