# Generated by Django 4.2.5 on 2023-09-15 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0011_device_data_source_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEconomicActivityAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type_id', models.CharField(max_length=100, verbose_name='経済活動量種別ID')),
                ('value', models.IntegerField(verbose_name='活動量')),
                ('activity_date', models.DateField(verbose_name='活動日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'DailyEconomicActivityAmount',
                'verbose_name_plural': 'DailyEconomicActivityAmounts',
            },
        ),
        migrations.CreateModel(
            name='EconomicActivityUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'EconomicActivityUnit',
                'verbose_name_plural': 'EconomicActivityUnits',
            },
        ),
        migrations.RenameModel(
            old_name='SalesType',
            new_name='EconomicActivityType',
        ),
        migrations.AlterModelOptions(
            name='economicactivitytype',
            options={'verbose_name': 'EconomicActivityType', 'verbose_name_plural': 'EconomicActivityTypes'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='sales_type_id',
        ),
        migrations.AddField(
            model_name='device',
            name='economic_activity_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.economicactivitytype', verbose_name='経済活動量種別ID'),
        ),
        migrations.DeleteModel(
            name='DailySales',
        ),
    ]
