# Generated by Django 4.2.5 on 2023-09-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0012_dailyeconomicactivityamount_economicactivityunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicactivitytype',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.economicactivityunit', verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='dailyeconomicactivityamount',
            name='activity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.economicactivitytype', verbose_name='経済活動量種別ID'),
        ),
    ]
