# Generated by Django 4.2.5 on 2023-09-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0012_alter_dataperdate_user_id_alter_dataperhour_user_id_and_more'),
        ('ihiapp', '0013_economicactivitytype_unit_and_more'),
    ]

    operations = [
    ]
