# Generated by Django 4.2.5 on 2023-09-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0014_merge_20230920_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyeconomicactivityamount',
            options={'verbose_name': '経済活動量', 'verbose_name_plural': '経済活動量'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'm.データ取得対象', 'verbose_name_plural': 'm.データ取得対象'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'm.デバイス種類', 'verbose_name_plural': 'm.デバイス種類'},
        ),
        migrations.AlterModelOptions(
            name='deviceunitprice',
            options={'verbose_name': 'm.単価情報', 'verbose_name_plural': 'm.単価情報'},
        ),
        migrations.AlterModelOptions(
            name='economicactivitytype',
            options={'verbose_name': '経済活動量種別', 'verbose_name_plural': '経済活動量種別'},
        ),
        migrations.AlterModelOptions(
            name='economicactivityunit',
            options={'verbose_name': 'm.経済活動量単位', 'verbose_name_plural': 'm.経済活動量単位'},
        ),
        migrations.AlterModelOptions(
            name='environmentaltype',
            options={'verbose_name': 'm.環境種類', 'verbose_name_plural': 'm.環境種類'},
        ),
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name': 'm.エッジデバイス(ゲートウェイ)', 'verbose_name_plural': 'm.エッジデバイス(ゲートウェイ)'},
        ),
        migrations.AlterModelOptions(
            name='mdevice',
            options={'verbose_name': 'マスタデバイス', 'verbose_name_plural': 'マスタデバイス'},
        ),
        migrations.AlterModelOptions(
            name='monthlycosttarget',
            options={'verbose_name': '月次目標', 'verbose_name_plural': '月次目標'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'm.単位', 'verbose_name_plural': 'm.単位'},
        ),
    ]
