# Generated by Django 4.2.5 on 2023-09-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0015_alter_dailyeconomicactivityamount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicactivitytype',
            name='unit',
        ),
    ]
