# Generated by Django 4.2.5 on 2023-09-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0016_remove_economicactivitytype_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyeconomicactivityamount',
            unique_together={('activity_type_id', 'activity_date')},
        ),
    ]
