# Generated by Django 4.2.5 on 2023-09-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0017_alter_dailyeconomicactivityamount_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economicactivitytype',
            options={'verbose_name': 'm.経済活動量種別', 'verbose_name_plural': 'm.経済活動量種別'},
        ),
    ]
