# Generated by Django 4.2.5 on 2023-09-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0018_alter_economicactivitytype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicactivityunit',
            name='user_id',
        ),
    ]
