# Generated by Django 4.2.6 on 2023-11-01 02:43

import uuid

import django.db.models.deletion
import ihiapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_add_demo_account'),
        ('ihiapp', '0020_alter_dataperdate_electrical_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushLogApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', ihiapp.models.EncryptedCharField(blank=True, max_length=512, null=True, unique=True)),
                ('hashed_key', models.CharField(max_length=512, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='会社ID')),
            ],
        ),
    ]
