# Generated by Django 4.2.6 on 2023-11-01 07:44

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_and_set_pushlog_api(apps, schema_editor):
    Gateway = apps.get_model("ihiapp", "gateway")
    User = apps.get_model("users", "user")
    PushlogApi = apps.get_model("ihiapp", "pushlogapi")

    for gateway in Gateway.objects.all():
        try:
            user = User.objects.get(pk=gateway.user_id.pk)
            if user.pushlog_api_key is not None:
                # モデルのカスタムsave()がマイグレーション時に呼ばれないため、
                # ここではハッシュ化したapi keyの値を設定する必要がある
                pepper = settings.ENCRYPTION_KEY
                hashed_key = hashlib.sha256((user.pushlog_api_key + pepper).encode()).hexdigest()

                # 同じ hashed_key を持つ PushlogApi が存在しない場合のみ作成
                if not PushlogApi.objects.filter(hashed_key=hashed_key).exists():
                    pushlog_api = PushlogApi.objects.create(
                        key=user.pushlog_api_key,
                        company=user.company_id,
                        hashed_key=hashed_key
                    )
                else:
                    pushlog_api = PushlogApi.objects.get(hashed_key=hashed_key)

                gateway.pushlog_api_id = pushlog_api.id
                gateway.save()
        except User.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0022_device_pushlog_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushlogapi',
            options={'verbose_name': 'PushLogApi', 'verbose_name_plural': 'PushLogApi'},
        ),
        migrations.AddField(
            model_name='gateway',
            name='pushlog_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.pushlogapi', verbose_name='PushLog API'),
        ),
        # migrations.RunPython(
        #     create_and_set_pushlog_api, reverse_code=migrations.RunPython.noop
        # ),
    ]
