# Generated by Django 4.2.6 on 2023-11-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0024_dataperdate_pushlog_api_dataperhour_pushlog_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_id',
        ),
    ]
