# Generated by Django 4.2.6 on 2023-11-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0025_remove_device_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataperdate',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dataperhour',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='datapermonth',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dataperyear',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='devicedataperdate',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='devicedataperhour',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='devicedatapermonth',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='devicedataperyear',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='jcreditapplication',
            name='user_id',
        ),
    ]
