# Generated by Django 4.2.7 on 2023-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0026_remove_dataperdate_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_integrated_value',
            field=models.BooleanField(default=True, verbose_name='データは積算値である（瞬間値でない）'),
        ),
    ]
