# Generated by Django 4.2.7 on 2023-11-15 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_hashed_pushlog_api_key_and_more'),
        ('ihiapp', '0027_device_is_integrated_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='会社ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(verbose_name='先祖から子孫までの深さ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='ihiapp.entity', verbose_name='先祖エンティティID')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='ihiapp.entity', verbose_name='子孫エンティティID')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_type', models.CharField(choices=[('year', '年'), ('month', '月'), ('date', '日'), ('hour', '時間')], max_length=10, verbose_name='日付タイプ')),
                ('value', models.FloatField(verbose_name='値')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('get_data_at', models.DateTimeField(verbose_name='取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.datatype', verbose_name='データタイプID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.entity', verbose_name='エンティティID')),
            ],
            options={
                'verbose_name': 'データ',
                'verbose_name_plural': 'データ',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.datatype', verbose_name='データタイプID'),
        ),
        migrations.AddField(
            model_name='device',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.entity', verbose_name='エンティティID'),
        ),
    ]
