# Generated by Django 4.2.7 on 2023-11-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0028_datatype_entity_datastructure_data_device_data_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'データタイプ', 'verbose_name_plural': 'データタイプ'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'エンティティ', 'verbose_name_plural': 'エンティティ'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_type',
        ),
    ]
