# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0029_alter_datatype_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastructure',
            options={'verbose_name': 'データ構造', 'verbose_name_plural': 'データ構造'},
        ),
    ]
