# Generated by Django 4.2.7 on 2023-12-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_companyuser'),
        ('ihiapp', '0030_alter_datastructure_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycosttarget',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業ID'),
        ),
    ]
