# Generated by Django 4.2.7 on 2023-11-29 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0030_alter_datastructure_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'm.燃料種類',
                'verbose_name_plural': 'm.燃料種類',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='specific_gravity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='比重'),
        ),
        migrations.AddField(
            model_name='device',
            name='liquid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.liquidtype', verbose_name='燃料種類'),
        ),
    ]
