# Generated by Django 4.2.7 on 2023-11-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0031_liquidtype_device_specific_gravity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='liquid_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='specific_gravity',
        ),
        migrations.DeleteModel(
            name='LiquidType',
        ),
    ]
