# Generated by Django 4.2.7 on 2023-12-07 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0031_monthlycosttarget_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycosttarget',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
