# Generated by Django 4.2.7 on 2023-12-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_companyuser'),
        ('ihiapp', '0032_alter_monthlycosttarget_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycosttarget',
            unique_together={('company', 'year', 'month', 'target_type')},
        ),
    ]
