# Generated by Django 4.2.7 on 2023-11-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0033_liquidtype_device_liquid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='specific_gravity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='比重'),
        ),
    ]
