# Generated by Django 4.2.7 on 2023-12-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_companyuser'),
        ('ihiapp', '0033_alter_monthlycosttarget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicactivitytype',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='会社ID'),
        ),
    ]
