# Generated by Django 4.2.7 on 2023-12-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0034_device_specific_gravity'),
        ('ihiapp', '0035_alter_economicactivitytype_user_id'),
    ]

    operations = [
    ]
