# Generated by Django 4.2.8 on 2023-12-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0036_merge_20231208_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_integrated_value',
        ),
    ]
