# Generated by Django 4.2.8 on 2023-12-19 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0037_remove_device_is_integrated_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('電気', '電気'), ('水', '水'), ('燃料', '燃料'), ('CO2', 'CO2')], max_length=20, verbose_name='名称')),
                ('value', models.CharField(choices=[('円/kWh', '円/kWh'), ('円/m3', '円/m3'), ('円/t-CO2', '円/t-CO2'), ('t-CO2/kWh', 't-CO2/kWh'), ('t-CO2/m3', 't-CO2/m3')], max_length=20, verbose_name='単位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '単価タイプ',
                'verbose_name_plural': '単価タイプ',
            },
        ),
        migrations.CreateModel(
            name='StandartUnitPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(verbose_name='値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.pricetype')),
            ],
            options={
                'verbose_name': 'm.標準単価',
                'verbose_name_plural': 'm.標準単価',
            },
        ),
    ]
