# Generated by Django 4.2.8 on 2023-12-20 02:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0038_pricetype_standartunitprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetype',
            options={'verbose_name': 'm.単価タイプ', 'verbose_name_plural': 'm.単価タイプ'},
        ),
        migrations.RenameField(
            model_name='pricetype',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='pricetype',
            old_name='value',
            new_name='unit',
        ),
        migrations.CreateModel(
            name='StandartUnitPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before', models.FloatField(verbose_name='変更前の値')),
                ('after', models.FloatField(verbose_name='変更後の値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.pricetype')),
            ],
            options={
                'verbose_name': 'm.標準単価履歴',
                'verbose_name_plural': 'm.標準単価履歴',
            },
        ),
    ]
