# Generated by Django 4.2.8 on 2023-12-20 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_company_co2_unit_price_company_electric_unit_co2_and_more'),
        ('ihiapp', '0039_alter_pricetype_options_rename_name_pricetype_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('before', models.FloatField(verbose_name='変更前の値')),
                ('after', models.FloatField(verbose_name='変更後の値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='会社ID')),
            ],
            options={
                'verbose_name': 'm.単価変更履歴',
                'verbose_name_plural': 'm.単価変更履歴',
            },
        ),
        migrations.RemoveField(
            model_name='standartunitprice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='standartunitpricehistory',
            name='name',
        ),
        migrations.DeleteModel(
            name='PriceType',
        ),
        migrations.DeleteModel(
            name='StandartUnitPrice',
        ),
        migrations.DeleteModel(
            name='StandartUnitPriceHistory',
        ),
    ]
