# Generated by Django 4.2.8 on 2023-12-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0040_unitpricehistory_remove_standartunitprice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpricehistory',
            name='field',
            field=models.CharField(default='', max_length=20, verbose_name='フィールド名'),
        ),
    ]
