# Generated by Django 4.2.8 on 2023-12-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0041_unitpricehistory_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpricehistory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='unitpricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='変更日時'),
        ),
    ]
