# Generated by Django 4.2.8 on 2023-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0042_remove_unitpricehistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpricehistory',
            name='field',
            field=models.CharField(default='', max_length=30, verbose_name='フィールド名'),
        ),
        migrations.AlterField(
            model_name='unitpricehistory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名前'),
        ),
    ]
