# Generated by Django 4.2.8 on 2023-12-22 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0043_alter_unitpricehistory_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.entity', verbose_name='エンティティID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'ユーザーエンティティ権限',
                'verbose_name_plural': 'ユーザーエンティティ権限',
            },
        ),
    ]
