# Generated by Django 4.2.8 on 2023-12-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0043_alter_unitpricehistory_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='liquid_type',
            new_name='liquid_type_id',
        ),
    ]
