# Generated by Django 4.2.8 on 2023-12-26 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0044_rename_liquid_type_device_liquid_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='値'),
        ),
    ]
