# Generated by Django 4.2.8 on 2023-12-25 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihiapp', '0044_userentitypermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userentitypermission',
            unique_together={('user', 'entity')},
        ),
    ]
