# Generated by Django 4.2.8 on 2023-12-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0044_rename_liquid_type_device_liquid_type_id'),
        ('ihiapp', '0045_alter_userentitypermission_unique_together'),
    ]

    operations = [
    ]
