# Generated by Django 4.2.8 on 2023-12-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0045_alter_data_price_alter_data_value'),
        ('ihiapp', '0046_merge_20231226_1402'),
    ]

    operations = [
    ]
