# Generated by Django 4.2.8 on 2023-12-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0047_merge_20231228_1128'),
        ('ihiapp', '0047_merge_20231228_1739'),
    ]

    operations = [
    ]
