# Generated by Django 4.2.9 on 2024-01-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0048_merge_20231229_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_type',
            field=models.CharField(choices=[('year', '年'), ('month', '月'), ('date', '日'), ('hour', '時間'), ('minute', '分')], max_length=10, verbose_name='日付タイプ'),
        ),
    ]
