# Generated by Django 4.2.8 on 2024-01-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0048_merge_20231229_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceunitprice',
            name='water_unit_co2',
            field=models.FloatField(default=0, verbose_name='水(t-CO2/m3)'),
        ),
    ]
