# Generated by Django 4.2.9 on 2024-01-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0049_alter_data_date_type'),
        ('ihiapp', '0049_deviceunitprice_water_unit_co2'),
    ]

    operations = [
    ]
