# Generated by Django 4.2.8 on 2024-01-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0049_deviceunitprice_water_unit_co2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushlogapi',
            options={'verbose_name': 'm.APIキー', 'verbose_name_plural': 'm.APIキー'},
        ),
    ]
