# Generated by Django 4.2.9 on 2024-01-15 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_channelbasicunit_company_and_more'),
        ('ihiapp', '0050_merge_20240115_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='利用開始日時')),
                ('annual_plan_utility_cost', models.IntegerField(default=0, verbose_name='年間計画：光熱費')),
                ('annual_plan_electric', models.IntegerField(default=0, verbose_name='年間計画：電力量')),
                ('annual_plan_electric_reduce', models.IntegerField(default=0, verbose_name='年間計画：電力削減量')),
                ('annual_plan_co2_emissions', models.IntegerField(default=0, verbose_name='年間計画：CO2排出量')),
                ('annual_plan_co2_emissions_reduce', models.IntegerField(default=0, verbose_name='年間計画：CO2削減量')),
                ('carbon_credit', models.IntegerField(default=0, verbose_name='カーボンクレジット量')),
                ('carbon_credit_price', models.IntegerField(default=0, verbose_name='カーボンクレジット価格')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
                ('gateway_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gateway', verbose_name='ゲートウェイ')),
            ],
            options={
                'verbose_name': 'チャンネル用Gateway単位の設定',
                'verbose_name_plural': 'チャンネル用Gateway単位の設定',
            },
        ),
        migrations.CreateModel(
            name='ChannelBasicUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=6, verbose_name='対象年')),
                ('month', models.CharField(max_length=6, verbose_name='対象月')),
                ('value', models.FloatField(default=0, verbose_name='値')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
                ('gateway_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gateway', verbose_name='ゲートウェイ')),
            ],
            options={
                'verbose_name': 'チャンネル原単位設定',
                'verbose_name_plural': 'チャンネル原単位設定',
            },
        ),
        migrations.CreateModel(
            name='ChannelAdapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_no', models.IntegerField(default=0, verbose_name='チャンネル番号')),
                ('channel_name', models.CharField(max_length=30, verbose_name='チャンネル名')),
                ('equation_str', models.CharField(max_length=30, verbose_name='計算式')),
                ('utility_cost_price', models.FloatField(default=0, verbose_name='光熱費単価')),
                ('co2_emissions_current', models.FloatField(default=0, verbose_name='CO2排出量:現状')),
                ('co2_emissions_baseline', models.FloatField(default=0, verbose_name='CO2排出量:再エネのベースライン')),
                ('co2_emissions_improvement_rate', models.FloatField(default=0, verbose_name='CO2排出量:対ベースライン改善割合')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
                ('device_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.device', verbose_name='デバイス型番')),
                ('entity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.entity', verbose_name='エンティティ')),
                ('gateway_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gateway', verbose_name='ゲートウェイID')),
            ],
            options={
                'verbose_name': 'チャンネル',
                'verbose_name_plural': 'チャンネル',
            },
        ),
    ]
