# Generated by Django 4.2.9 on 2024-01-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0052_alter_channeladapter_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeladapter',
            name='gateway_id',
        ),
    ]
