# Generated by Django 4.2.9 on 2024-01-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0053_remove_channeladapter_gateway_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDataPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_no', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.dataperhour')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelDataPerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_no', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.dataperdate')),
            ],
        ),
    ]
