# Generated by Django 4.2.9 on 2024-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0054_channeldataperhour_channeldataperdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladapter',
            name='co2_emissions_baseline',
            field=models.FloatField(default=0, null=True, verbose_name='CO2排出量:再エネのベースライン'),
        ),
        migrations.AlterField(
            model_name='channeldataperdate',
            name='channel_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='channeldataperhour',
            name='channel_no',
            field=models.CharField(max_length=10),
        ),
    ]
