# Generated by Django 4.2.9 on 2024-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0055_alter_channeladapter_co2_emissions_baseline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladapter',
            name='co2_emissions_baseline',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CO2排出量:再エネのベースライン'),
        ),
    ]
