# Generated by Django 4.2.9 on 2024-01-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0050_alter_pushlogapi_options'),
        ('ihiapp', '0056_alter_channeladapter_co2_emissions_baseline'),
    ]

    operations = [
    ]
