# Generated by Django 4.2.9 on 2024-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0057_merge_20240126_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='get_data_at',
            field=models.DateTimeField(db_index=True, verbose_name='取得日時'),
        ),
    ]
