# Generated by Django 4.2.9 on 2024-02-05 03:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0058_alter_data_get_data_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPerMinute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electrical_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電気/取得値(kW)')),
                ('electrical_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電気/料金(円)')),
                ('water_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水/取得値(L)')),
                ('water_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水/料金(円)')),
                ('fuel_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='燃料/取得値(L)')),
                ('fuel_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='燃料/料金(円)')),
                ('co2_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO2/取得値(t-CO2)')),
                ('co2_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO2/料金(円)')),
                ('energy_saving_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='省エネ創出(t-CO2)')),
                ('renewal_energy_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='再エネ創出(t-CO2)')),
                ('utility_costs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='光熱費(円)')),
                ('get_data_date', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0), verbose_name='取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='年')),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('date', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='時間')),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='分')),
                ('second', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='秒')),
                ('pushlog_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.pushlogapi', verbose_name='PUSHLOG API ID')),
            ],
            options={
                'verbose_name': '1-1. 合計値/分単位',
                'verbose_name_plural': '1-1. 合計値/分単位',
            },
        ),
        migrations.CreateModel(
            name='ChannelDataPerMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_no', models.CharField(max_length=10)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.dataperminute')),
            ],
        ),
    ]
