# Generated by Django 4.2.10 on 2024-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0060_annualplanvalue_gatewaystartdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeladapter',
            options={'verbose_name': 'グラフ接続情報', 'verbose_name_plural': 'グラフ接続情報'},
        ),
    ]
