# Generated by Django 4.2.10 on 2024-02-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0061_alter_channeladapter_options_and_more'),
    ]

    operations = [
    ]
