# Generated by Django 4.2.10 on 2024-02-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0062_rename_graph_name_channeladapter_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladapter',
            name='channel_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='グラフ名'),
        ),
        migrations.AlterField(
            model_name='channeladapter',
            name='channel_no',
            field=models.IntegerField(default=0, verbose_name='グラフ番号'),
        ),
    ]
