# Generated by Django 4.2.10 on 2024-02-09 09:49

from django.db import migrations, models
import django.db.models.deletion
import ihiapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_agreed_to_terms_of_service'),
        ('ihiapp', '0063_alter_channeladapter_channel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlanValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utility_cost', models.FloatField(default=0.0, verbose_name='光熱費')),
                ('electric', models.FloatField(default=0.0, verbose_name='電力量')),
                ('electric_reduce', models.FloatField(default=0.0, verbose_name='電力削減量')),
                ('co2_emissions', models.FloatField(default=0.0, verbose_name='CO2排出量')),
                ('co2_emissions_reduce', models.FloatField(default=0.0, verbose_name='CO2削減量')),
                ('carbon_credit', models.FloatField(default=0.0, verbose_name='カーボンクレジット量')),
                ('carbon_credit_price', models.FloatField(default=0.0, verbose_name='カーボンクレジット価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '年間計画値',
                'verbose_name_plural': '年間計画値',
            },
        ),
        migrations.AlterModelOptions(
            name='gatewaystartdate',
            options={'verbose_name': 'ゲートウェイの利用開始日', 'verbose_name_plural': 'ゲートウェイの利用開始日'},
        ),
        migrations.AlterField(
            model_name='channeladapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gatewaystartdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='gatewaystartdate',
            name='started_at',
            field=models.DateField(default=ihiapp.models.get_current_date, verbose_name='利用開始日'),
        ),
        migrations.DeleteModel(
            name='AnnualPlanValue',
        ),
    ]
