# Generated by Django 4.2.10 on 2024-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0065_alter_annualplanvalues_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladapter',
            name='is_co2_emissions_baseline',
            field=models.BooleanField(default=True, verbose_name='CO2排出量:再エネのベースラインを使用するか'),
        ),
        migrations.AlterField(
            model_name='channeladapter',
            name='co2_emissions_improvement_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CO2排出量:対ベースライン改善割合'),
        ),
    ]
