# Generated by Django 4.2.10 on 2024-02-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0066_channeladapter_is_co2_emissions_baseline_and_more'),
        ('ihiapp', '0066_gatewaymaster_registeredlimit_gatewayregistration'),
    ]

    operations = [
    ]
