# Generated by Django 4.2.10 on 2024-02-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0067_merge_20240215_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewayregistration',
            options={'verbose_name': 'ゲートウェイ登録情報', 'verbose_name_plural': 'ゲートウェイ登録情報'},
        ),
        migrations.AlterField(
            model_name='gatewayregistration',
            name='gateway_master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ihiapp.gatewaymaster', verbose_name='ゲートウェイマスタ'),
        ),
    ]
