# Generated by Django 4.2.10 on 2024-02-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0068_alter_gatewayregistration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushlogapi',
            name='company',
        ),
    ]
