# Generated by Django 4.2.10 on 2024-02-16 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_agreed_to_terms_of_service'),
        ('ihiapp', '0069_remove_pushlogapi_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeladapter',
            name='device_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihiapp.device', verbose_name='デバイス型番'),
        ),
        migrations.AlterField(
            model_name='channeladapter',
            name='entity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihiapp.entity', verbose_name='CHエンティティ'),
        ),
    ]
