# Generated by Django 4.2.10 on 2024-02-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0070_alter_channeladapter_device_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyeconomicactivityamount',
            name='activity_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.economicactivitytype', verbose_name='経済活動量種別ID'),
        ),
    ]
