# Generated by Django 4.2.10 on 2024-02-16 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_agreed_to_terms_of_service'),
        ('ihiapp', '0070_alter_channeladapter_device_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_name', models.CharField(default='工程', max_length=100, verbose_name='工程名')),
                ('channel_name', models.CharField(max_length=100, verbose_name='チャンネル名')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='取得開始日時')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='取得終了日時')),
                ('electric_value', models.FloatField(default=0.0, verbose_name='電力量')),
                ('co2_emissions', models.FloatField(default=0.0, verbose_name='CO2排出量')),
                ('scope_no', models.IntegerField(default=1, verbose_name='Scope区分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': 'カーボンフットプリント',
                'verbose_name_plural': 'カーボンフットプリント',
            },
        ),
    ]
