# Generated by Django 4.2.10 on 2024-02-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_agreed_to_terms_of_service'),
        ('ihiapp', '0071_alter_dailyeconomicactivityamount_activity_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyeconomicactivityamount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='会社ID'),
        ),
    ]
