# Generated by Django 4.2.10 on 2024-02-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0072_alter_carbonfootprint_company_id'),
        ('ihiapp', '0072_dailyeconomicactivityamount_company'),
    ]

    operations = [
    ]
