# Generated by Django 4.2.10 on 2024-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0073_merge_20240219_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualplanvalues',
            name='carbon_credit',
            field=models.FloatField(default=0.0, verbose_name='カーボンクレジット料（円）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='carbon_credit_price',
            field=models.FloatField(default=0.0, verbose_name='カーボンクレジット価格（円/t-CO2）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='co2_emissions',
            field=models.FloatField(default=0.0, verbose_name='CO2排出量（t-CO2）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='co2_emissions_reduce',
            field=models.FloatField(default=0.0, verbose_name='CO2削減量（t-CO2）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='electric',
            field=models.FloatField(default=0.0, verbose_name='電力量（kWh）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='electric_reduce',
            field=models.FloatField(default=0.0, verbose_name='電力削減量（kWh）'),
        ),
        migrations.AlterField(
            model_name='annualplanvalues',
            name='utility_cost',
            field=models.FloatField(default=0.0, verbose_name='光熱費（円）'),
        ),
    ]
