# Generated by Django 4.2.10 on 2024-02-23 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0074_alter_annualplanvalues_carbon_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額'),
        ),
    ]
