# Generated by Django 4.2.10 on 2024-02-24 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0075_alter_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co2EmissionsFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('no', models.IntegerField(default=0, verbose_name='番号')),
                ('factor', models.FloatField(default=0.0, verbose_name='係数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'CO2排出係数',
                'verbose_name_plural': 'CO2排出係数',
            },
        ),
    ]
