# Generated by Django 4.2.10 on 2024-02-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0076_co2emissionsfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaymaster',
            name='connected',
            field=models.BooleanField(default=False, verbose_name='接続状態'),
        ),
    ]
