# Generated by Django 4.2.10 on 2024-02-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0077_gatewaymaster_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaymaster',
            name='is_instantaneous',
            field=models.BooleanField(default=False, verbose_name='瞬時値かどうか'),
        ),
    ]
