# Generated by Django 4.2.10 on 2024-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0078_gatewaymaster_is_instantaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaymaster',
            name='license_limit',
            field=models.DateField(blank=True, null=True, verbose_name='利用可能期限'),
        ),
        migrations.AlterField(
            model_name='gatewaymaster',
            name='license_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ライセンス種別'),
        ),
    ]
