# Generated by Django 4.2.10 on 2024-03-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0079_alter_gatewaymaster_license_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeladapter',
            name='entity_id',
        ),
    ]
