# Generated by Django 4.2.11 on 2024-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0081_alter_device_input_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_instantaneous',
            field=models.BooleanField(default=False, verbose_name='瞬時値（True）/積算値（False）'),
        ),
    ]
