# Generated by Django 4.2.11 on 2024-03-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_affiliation'),
        ('ihiapp', '0082_device_is_instantaneous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaymaster',
            name='is_instantaneous',
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.datatype', verbose_name='データタイプID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company', verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='environmental_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ihiapp.environmentaltype', verbose_name='環境タイプID'),
        ),
    ]
