# Generated by Django 4.2.11 on 2024-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0083_remove_gatewaymaster_is_instantaneous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplanvalues',
            name='utility_cost_reduce',
            field=models.FloatField(default=0.0, verbose_name='光熱費削減量（円）'),
        ),
    ]
