# Generated by Django 4.2.10 on 2024-03-28 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_companyuser_unique_together'),
        ('ihiapp', '0084_annualplanvalues_utility_cost_reduce'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUploadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='ファイルサイズ（バイト）')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': 'CSVアップロード履歴',
                'verbose_name_plural': 'CSVアップロード履歴',
            },
        ),
    ]
