# Generated by Django 4.2.10 on 2024-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0085_csvuploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2emissionsfactor',
            name='region_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='地名'),
        ),
    ]
