# Generated by Django 4.2.11 on 2024-04-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0085_csvuploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayregistration',
            name='alt_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ゲートウェイ名:企業に紐付け'),
        ),
    ]
