# Generated by Django 4.2.11 on 2024-04-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0086_co2emissionsfactor_region_name'),
        ('ihiapp', '0086_gatewayregistration_alt_name'),
    ]

    operations = [
    ]
