# Generated by Django 4.1.7 on 2023-03-13 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='企業名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ権限')),
                ('is_staff', models.BooleanField(default=True, verbose_name='スタッフ権限')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='アカウント作成日時')),
                ('password_changed', models.BooleanField(default=False, verbose_name='パスワードを変更したか')),
                ('password_changed_date', models.DateTimeField(blank=True, null=True, verbose_name='最終パスワード変更日時')),
                ('electric_unit_price', models.IntegerField(default=0, verbose_name='電気(円/kWh)')),
                ('water_unit_price', models.IntegerField(default=0, verbose_name='水(円/m3)')),
                ('fuel_unit_price', models.IntegerField(default=0, verbose_name='燃料(円/m3)')),
                ('co2_unit_price', models.IntegerField(default=0, verbose_name='CO2(円/t-CO2)')),
                ('electric_unit_co2', models.FloatField(default=0, verbose_name='電気(t-CO2/kWh)')),
                ('fuel_unit_co2', models.FloatField(default=0, verbose_name='燃料(t-CO2/m3)')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='企業')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'verbose_name_plural': 'ユーザ',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
