# Generated by Django 4.2.1 on 2023-06-08 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_useractivationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 7, 53, 59, 455768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useractivationtoken',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
