# Generated by Django 4.2.1 on 2023-06-09 06:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useractivationtoken_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivationtoken',
            name='expiration_date',
            field=models.DateTimeField(default=users.models.default_expiration_date),
        ),
    ]
