# Generated by Django 4.2.3 on 2023-08-02 01:59

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_options_alter_notification_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushlog_api_key',
            field=users.models.EncryptedCharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
