# Generated by Django 4.2.3 on 2023-08-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_pushlog_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_revenue',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='1日あたりの売上'),
        ),
    ]
