# Generated by Django 4.2.5 on 2023-09-22 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_economic_activity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
