# Generated by Django 4.2.6 on 2023-10-18 08:18

import os

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_hashed_pushlog_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='デモユーザーかどうか'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_demo', True)), fields=('is_demo',), name='unique_true_is_demo'),
        ),
    ]
