# Generated by Django 4.2.6 on 2023-10-18 08:18

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_demo_account(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    User = apps.get_model('users', 'User')
    Gateway = apps.get_model('ihiapp', 'Gateway')
    Device = apps.get_model('ihiapp', 'Device')
    EconomicActivityUnit = apps.get_model('ihiapp', 'EconomicActivityUnit')

    economic_activity_unit = EconomicActivityUnit.objects.all().first()
    demo_company = Company.objects.create(
        name='デモ企業',
        economic_activity_unit=economic_activity_unit,
    )
    hashed_password = make_password(os.environ.get('DEMO_ACCOUNT_PASSWORD'))
    demo_user = User.objects.create(
        username='デモユーザー',
        email='demo@bizfreak.co.jp',
        is_active=True,
        is_staff=False,
        is_demo=True,
        password=hashed_password,
        company_id=demo_company
    )
    demo_company.admin_user_id = demo_user
    demo_company.save()

    demo_gateway = Gateway.objects.create(
        id = '0',
        name = 'デモゲートウェイ',
        model = 'デモモデル',
        is_activated = True,
        firmware_version = 1,
        user_id = demo_user
    )
    Device.objects.create(
        name = 'デモデバイス01',
        data_source_name = 'デモ取得対象01',
        device_number = 1,
        gateway_id = demo_gateway,
        user_id = demo_user,
        enable_data_collection = True,
    )
    Device.objects.create(
        name = 'デモデバイス02',
        data_source_name = 'デモ取得対象01',
        device_number = 2,
        gateway_id = demo_gateway,
        user_id = demo_user,
        enable_data_collection = True,
    )
    Device.objects.create(
        name = 'デモデバイス03',
        data_source_name = 'デモ取得対象03',
        device_number = 3,
        gateway_id = demo_gateway,
        user_id = demo_user,
        enable_data_collection = True,
    )

def reverse_create_demo_account(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    User = apps.get_model('users', 'User')
    Gateway = apps.get_model('ihiapp', 'Gateway')
    Device = apps.get_model('ihiapp', 'Device')

    demo_user = User.objects.filter(is_demo=True).first()
    if demo_user:
        Device.objects.filter(user_id=demo_user).delete()
        Gateway.objects.filter(user_id=demo_user).delete()
        Company.objects.filter(admin_user_id=demo_user).delete()
        demo_user.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_demo_user_unique_true_is_demo'),
    ]

    operations = [
        migrations.RunPython(create_demo_account, reverse_create_demo_account),
    ]
