# Generated by Django 4.2.7 on 2023-11-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_add_demo_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_pushlog_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pushlog_api_key',
        ),
    ]
