# Generated by Django 4.2.8 on 2023-12-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_add_demo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='アカウントのロック状態'),
        ),
    ]
