# Generated by Django 4.2.7 on 2023-11-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0030_alter_datastructure_options'),
        ('users', '0013_remove_user_hashed_pushlog_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='root_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_company', to='ihiapp.entity', verbose_name='ルートエンティティ'),
        ),
    ]
