# Generated by Django 4.2.8 on 2023-12-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_companyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='co2_unit_price',
            field=models.IntegerField(default=0, verbose_name='CO2(円/t-CO2)'),
        ),
        migrations.AddField(
            model_name='company',
            name='electric_unit_co2',
            field=models.FloatField(default=0, verbose_name='電気(t-CO2/kWh)'),
        ),
        migrations.AddField(
            model_name='company',
            name='electric_unit_price',
            field=models.IntegerField(default=0, verbose_name='電気(円/kWh)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_unit_co2',
            field=models.FloatField(default=0, verbose_name='燃料(t-CO2/m3)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_unit_price',
            field=models.IntegerField(default=0, verbose_name='燃料(円/m3)'),
        ),
        migrations.AddField(
            model_name='company',
            name='water_unit_price',
            field=models.IntegerField(default=0, verbose_name='水(円/m3)'),
        ),
    ]
