# Generated by Django 4.2.8 on 2023-12-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_locked'),
        ('users', '0016_company_co2_unit_price_company_electric_unit_co2_and_more'),
    ]

    operations = [
    ]
