# Generated by Django 4.2.8 on 2024-01-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_company_co2_unit_price_company_electric_unit_co2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='batch_enabled',
            field=models.BooleanField(default=False, verbose_name='バッチ処理の有効化'),
        ),
    ]
