# Generated by Django 4.2.8 on 2024-01-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_company_batch_enabled'),
        ('users', '0017_merge_20231222_1735'),
    ]

    operations = [
    ]
