# Generated by Django 4.2.8 on 2024-01-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihiapp', '0049_deviceunitprice_water_unit_co2'),
        ('users', '0018_company_water_unit_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='root_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_company', to='ihiapp.entity', verbose_name='ルートエンティティ'),
        ),
    ]
