# Generated by Django 4.2.8 on 2024-01-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_company_root_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': '企業とユーザーの紐付け', 'verbose_name_plural': '企業とユーザーの紐付け'},
        ),
    ]
