# Generated by Django 4.2.9 on 2024-01-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20240109_1913'),
        ('users', '0019_alter_company_root_entity'),
    ]

    operations = [
    ]
