# Generated by Django 4.2.9 on 2024-01-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_channelsetting_channelbasicunit_channel'),
        ('users', '0020_merge_20240115_1617'),
    ]

    operations = [
    ]
