# Generated by Django 4.2.9 on 2024-01-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_20240115_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelbasicunit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='channelbasicunit',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='channelsetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='channelsetting',
            name='gateway',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelBasicUnit',
        ),
        migrations.DeleteModel(
            name='ChannelSetting',
        ),
    ]
