# Generated by Django 4.2.9 on 2024-01-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_companyuser_options'),
        ('users', '0022_remove_channelbasicunit_company_and_more'),
    ]

    operations = [
    ]
