# Generated by Django 4.2.9 on 2024-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20240126_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreed_to_terms_of_service',
            field=models.BooleanField(default=False, verbose_name='利用規約に同意したか'),
        ),
    ]
