# Generated by Django 4.2.10 on 2024-02-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_agreed_to_terms_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属'),
        ),
    ]
