# Generated by Django 4.2.11 on 2024-03-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
