# Generated by Django 4.2.10 on 2024-03-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_company_admin_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('company', 'user')},
        ),
    ]
